# Change these first
owner: digitalmalayali # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Digital Malayali - ML
    url: https://digitalmalayali.in
  - name: Digital Malayali - EN
    url: https://en.digitalmalayali.in
  - name: Radio
    url: https://radio.digitalmalayali.in/public/stream
  - name: Memes
    url: https://memes.digitalmalayali.in
  - name: Privacy Policy Generator
    url: https://free-privacy-policy-generator.digitalmalayali.in
  - name: Malayalam Privacy Policy Generator
    url: https://malayalam-privacy-policy-generator.digitalmalayali.in
  - name: Pappadam
    url: https://pappadam.digitalmalayali.in
  - name: Malayalam Invoice Generator
    url: https://malayalam-invoice-generator.digitalmalayali.in

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.digitalmalayali.in
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "Find the status of all **Digital Malayali** websites here!"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
